import {
  ActivityIcon,
  BarChart3Icon,
  BotIcon,
  CheckIcon,
  GlobeIcon,
  KeyIcon,
  LayersIcon,
  LinkIcon,
  ScanSearchIcon,
  SearchIcon,
  ShieldCheckIcon,
  ZapIcon,
} from "lucide-react";
import Link from "next/link";
import { Suspense } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { PLAN_CATALOG, PLAN_ORDER } from "@/lib/plans";
import { cn } from "@/lib/utils";
import { ChatOnboarding, ChatOnboardingSkeleton } from "./chat";

const FEATURES = [
  {
    icon: BotIcon,
    title: "AI Chat",
    description: "Ask anything about your site's SEO in plain language",
    color: "text-blue-400",
  },
  {
    icon: ScanSearchIcon,
    title: "Page Analysis",
    description: "Deep content and structure inspection per page",
    color: "text-cyan-400",
  },
  {
    icon: SearchIcon,
    title: "Technical SEO",
    description: "Robots.txt, sitemap, and crawlability validation",
    color: "text-teal-400",
  },
  {
    icon: ZapIcon,
    title: "Core Web Vitals",
    description: "PageSpeed scores, LCP, FID, and CLS tracking",
    color: "text-green-400",
  },
  {
    icon: ShieldCheckIcon,
    title: "Security Headers",
    description: "HTTPS, CSP, HSTS, and header auditing",
    color: "text-emerald-400",
  },
  {
    icon: BarChart3Icon,
    title: "SERP Rankings",
    description: "Track keyword positions across search engines",
    color: "text-violet-400",
  },
  {
    icon: LinkIcon,
    title: "Trust & Backlinks",
    description: "Domain authority and backlink profile analysis",
    color: "text-purple-400",
  },
  {
    icon: KeyIcon,
    title: "Keyword Cannibalization",
    description: "Detect competing pages targeting the same keywords",
    color: "text-pink-400",
  },
  {
    icon: ActivityIcon,
    title: "AI Recommendations",
    description: "Prioritized, actionable fixes generated by AI",
    color: "text-yellow-400",
  },
  {
    icon: GlobeIcon,
    title: "Multi-Site Management",
    description: "Monitor and compare all your sites in one place",
    color: "text-orange-400",
  },
];

const METRIC_CHIPS = [
  { label: "PageSpeed", value: "94/100", delay: "0s" },
  { label: "LCP", value: "1.2s", delay: "1s" },
  { label: "Security", value: "A+", delay: "2s" },
  { label: "Backlinks", value: "12.4k", delay: "0.5s" },
];

const AUDIENCE_CARDS = [
  {
    audience: "Small Business",
    badge: "Starter — Free",
    headline: "Punch above your weight online",
    bullets: [
      "No SEO expertise required — just ask",
      "Instant technical audit on signup",
      "Fix critical issues in minutes, not weeks",
    ],
    accentClass: "border-blue-500/40 shadow-blue-500/10",
    buttonVariant: "outline" as const,
  },
  {
    audience: "Agency",
    badge: "Agency — $49/mo",
    headline: "Scale client SEO without scaling headcount",
    bullets: [
      "50 sites under one dashboard",
      "White-label-ready reporting",
      "5,000 AI messages per billing cycle",
    ],
    accentClass: "border-violet-500/40 shadow-violet-500/10",
    buttonVariant: "default" as const,
  },
  {
    audience: "Engineer",
    badge: "Pro — $8/mo intro",
    headline: "SEO tooling that speaks your language",
    bullets: [
      "JSON schema & structured data validation",
      "Core Web Vitals regression tracking",
      "API access for CI/CD integration",
    ],
    accentClass: "border-cyan-500/40 shadow-cyan-500/10",
    buttonVariant: "outline" as const,
  },
];

export default function Page() {
  return (
    <>
      <main>
        {/* ── Section 1: Hero ── */}
        <section className="relative flex min-h-screen flex-col items-center justify-center overflow-hidden px-4 text-center">
          {/* Grid background */}
          <div className="pointer-events-none absolute inset-0 bg-grid bg-grid-fade" />

          {/* Glow orbs */}
          <div className="glow-orb-blue pointer-events-none absolute -top-32 -left-32 h-[600px] w-[600px]" />
          <div className="glow-orb-purple pointer-events-none absolute -top-32 -right-32 h-[500px] w-[500px]" />

          {/* Content */}
          <div className="relative z-10 flex flex-col items-center gap-6 py-20">
            {/* Eyebrow */}
            <div className="flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-4 py-1.5 text-sm">
              <span className="inline-block h-2 w-2 animate-[pulse-glow_2s_ease-in-out_infinite] rounded-full bg-blue-400" />
              <span className="text-muted-foreground">
                AI-native SEO command center
              </span>
            </div>

            {/* Headline */}
            <h1 className="max-w-3xl font-bold text-5xl tracking-tighter md:text-7xl">
              Your site&apos;s SEO,{" "}
              <span className="block text-gradient-blue">
                command and control.
              </span>
            </h1>

            {/* Subheading */}
            <p className="max-w-xl text-balance text-muted-foreground text-xl">
              An AI agent that audits, ranks, and fixes your site&apos;s SEO —
              then explains every decision in plain language. No dashboards to
              decode.
            </p>

            {/* CTAs */}
            <div className="flex flex-wrap items-center justify-center gap-3">
              <Button
                className="glow-primary"
                nativeButton={false}
                render={<Link href="/onboarding" />}
                size="lg"
              >
                Start for free
              </Button>
              <Button
                nativeButton={false}
                render={<Link href="#features" />}
                size="lg"
                variant="outline"
              >
                See all features
              </Button>
            </div>

            {/* Trust note */}
            <p className="text-muted-foreground text-xs">
              No credit card required · Free tier includes 1 site &amp; 100 AI
              messages
            </p>

            {/* Floating metric chips */}
            <div className="mt-8 flex flex-wrap items-center justify-center gap-3">
              {METRIC_CHIPS.map((chip) => (
                <div
                  className="metric-chip flex items-center gap-2 rounded-full px-4 py-2 text-sm"
                  key={chip.label}
                  style={{
                    animation: `float-y 4s ease-in-out ${chip.delay} infinite`,
                  }}
                >
                  <span className="text-muted-foreground">{chip.label}</span>
                  <span className="font-semibold text-foreground">
                    {chip.value}
                  </span>
                </div>
              ))}
            </div>
          </div>

          {/* Bottom fade */}
          <div className="pointer-events-none absolute right-0 bottom-0 left-0 h-32 bg-gradient-to-t from-background to-transparent" />
        </section>

        {/* ── Section 2: Feature Showcase ── */}
        <section className="px-4 py-24" id="features">
          <div className="mx-auto max-w-6xl">
            {/* Section header */}
            <div className="mb-12 flex flex-col items-center gap-3 text-center">
              <span className="text-muted-foreground text-sm uppercase tracking-widest">
                Full toolkit
              </span>
              <h2 className="font-bold text-3xl tracking-tight md:text-4xl">
                Everything your site needs to rank
              </h2>
              <p className="max-w-lg text-balance text-muted-foreground">
                From technical audits to AI-generated fix plans — Seoteric
                covers the full SEO stack in one AI conversation.
              </p>
            </div>

            {/* Feature cards grid */}
            <div className="grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-5">
              {FEATURES.map((feature) => (
                <div
                  className="glass-card-interactive group rounded-xl p-4"
                  key={feature.title}
                >
                  <div className="mb-3 inline-flex rounded-lg bg-white/5 p-2">
                    <feature.icon className={cn("h-5 w-5", feature.color)} />
                  </div>
                  <h3 className="mb-1 font-medium text-sm">{feature.title}</h3>
                  <p className="text-muted-foreground text-xs leading-relaxed">
                    {feature.description}
                  </p>
                </div>
              ))}

              {/* Filler "More coming" card */}
              <div className="glass-card rounded-xl p-4 opacity-40">
                <div className="mb-3 inline-flex rounded-lg bg-white/5 p-2">
                  <LayersIcon className="h-5 w-5 text-muted-foreground" />
                </div>
                <h3 className="mb-1 font-medium text-sm">More coming</h3>
                <p className="text-muted-foreground text-xs leading-relaxed">
                  New tools ship regularly
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* ── Section 3: Built For ── */}
        <section className="relative overflow-hidden px-4 py-24">
          {/* Center glow */}
          <div className="glow-orb-blue pointer-events-none absolute inset-0 mx-auto h-full w-full" />

          <div className="relative z-10 mx-auto max-w-6xl">
            <div className="mb-12 flex flex-col items-center gap-3 text-center">
              <span className="text-muted-foreground text-sm uppercase tracking-widest">
                Built for
              </span>
              <h2 className="font-bold text-3xl tracking-tight md:text-4xl">
                Whoever owns the site
              </h2>
              <p className="max-w-lg text-balance text-muted-foreground">
                Whether you&apos;re a solo founder, an agency, or a developer —
                Seoteric fits your workflow.
              </p>
            </div>

            <div className="grid grid-cols-1 gap-6 md:grid-cols-3">
              {AUDIENCE_CARDS.map((card) => (
                <div
                  className={cn(
                    "glass-card rounded-2xl p-6 shadow-lg",
                    card.accentClass
                  )}
                  key={card.audience}
                >
                  <Badge className="mb-4" variant="secondary">
                    {card.badge}
                  </Badge>
                  <p className="mb-1 font-medium text-muted-foreground text-sm">
                    {card.audience}
                  </p>
                  <h3 className="mb-4 font-semibold text-lg leading-snug">
                    {card.headline}
                  </h3>
                  <ul className="mb-6 flex flex-col gap-2">
                    {card.bullets.map((bullet) => (
                      <li
                        className="flex items-start gap-2 text-muted-foreground text-sm"
                        key={bullet}
                      >
                        <CheckIcon className="mt-0.5 h-4 w-4 shrink-0 text-primary" />
                        {bullet}
                      </li>
                    ))}
                  </ul>
                  <Button
                    className={cn(
                      card.buttonVariant === "default" && "glow-primary",
                      "w-full"
                    )}
                    nativeButton={false}
                    render={<Link href="/onboarding" />}
                    variant={card.buttonVariant}
                  >
                    Get started free
                  </Button>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ── Section 4: Pricing Teaser ── */}
        <section className="px-4 pt-12 pb-32">
          <div className="mx-auto max-w-6xl">
            <div className="rounded-2xl border border-white/10 bg-gradient-to-br from-primary/10 via-transparent to-violet-500/10 p-px">
              <div className="rounded-2xl bg-background/90 px-6 py-10 backdrop-blur-sm md:px-10">
                <div className="flex flex-col gap-10 lg:flex-row lg:items-center lg:justify-between">
                  {/* Left: copy */}
                  <div className="flex flex-col gap-4 lg:max-w-sm">
                    <span className="text-muted-foreground text-sm uppercase tracking-widest">
                      Pricing
                    </span>
                    <h2 className="font-bold text-3xl tracking-tight">
                      Start free. Scale when you need to.
                    </h2>
                    <p className="text-muted-foreground">
                      Every plan includes the full AI toolkit. Upgrade only when
                      your site count or usage grows.
                    </p>
                    <div className="flex flex-wrap gap-3">
                      <Button
                        className="glow-primary"
                        nativeButton={false}
                        render={<Link href="/onboarding" />}
                      >
                        Get started free
                      </Button>
                      <Button
                        nativeButton={false}
                        render={<Link href="/pricing" />}
                        variant="ghost"
                      >
                        Compare all plans →
                      </Button>
                    </div>
                  </div>

                  {/* Right: plan pills */}
                  <div className="flex flex-col gap-3 lg:min-w-[340px]">
                    {PLAN_ORDER.map((planId) => {
                      const plan = PLAN_CATALOG[planId];
                      const isPopular = plan.badge === "Popular";
                      const displayPrice = plan.introPrice
                        ? `${plan.introPrice.discounted}/mo`
                        : plan.price.replace("/month", "/mo");

                      return (
                        <div
                          className={cn(
                            "flex items-center justify-between rounded-xl border px-4 py-3",
                            isPopular
                              ? "glass-card border-primary/40 shadow-lg shadow-primary/10"
                              : "border-white/6 bg-white/3"
                          )}
                          key={planId}
                        >
                          <div className="flex items-center gap-3">
                            <span className="font-medium">{plan.name}</span>
                            {isPopular && (
                              <Badge className="text-xs" variant="default">
                                Popular
                              </Badge>
                            )}
                            {plan.introPrice && (
                              <span className="text-muted-foreground text-xs">
                                {plan.introPrice.label}
                              </span>
                            )}
                          </div>
                          <span
                            className={cn(
                              "font-semibold",
                              isPopular && "text-primary"
                            )}
                          >
                            {displayPrice}
                          </span>
                        </div>
                      );
                    })}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>

      <Suspense fallback={<ChatOnboardingSkeleton />}>
        <ChatOnboarding />
      </Suspense>
    </>
  );
}
